### ISSUE TITLE
new bug not icons

### ISSUE THREAD

**Issue by Eignar17** [folz/reaction-packs#1]
![captura de pantalla de 2016-04-22 08-11-17](https://cloud.githubusercontent.com/assets/8561550/14742437/d5995a08-0861-11e6-9dd4-440dfd9c941e.png)
not new icons

**Comment by folz** [comment]
Thank you for the report! I'm working on a fix.

**Comment by katesavage2001** [comment]
The site is also down: 
This site can’t be reached

www.reactionpacks.com’s server DNS address could not be found.

**Comment by daverag** [comment]
Still not fixed as of today?

**Comment by Eignar17** [comment]
no
